# Configuration file for EggHunt by Dartanman
# Make sure you do NOT put a / before any commands in the config.yml
Messages:
  NoPermission: '&cInsufficient permissions.'
  GetEgg: '&aYou have been given an egg. Place it somewhere for Players to find.'
  FoundEgg: '&aYou have found an egg! Total eggs found: {found}/{total}'
  AlreadyFound: '&cYou already found that egg!'
  CannotDestroy: '&cYou cannot destroy the eggs!'
  InvalidArgs: '&cInvalid args. Try /egghunt help'
  SuccessfullyAdded: '&aEgg successfully added.'
EggInfo:
  EggName: '&d&lEaster Egg'
  EggLore:
    - '&aPlace this egg somewhere for Players to find!'
    - '&aDon't make it too obvious, though. It shouldn't be easy!'
BroadcastWhenAllFound:
  Enabled: true
  Message: '&9[EggHunt] &6{player} &ahas found all of the eggs!'
CommandRewardsForAllFound:
  Enabled: true
  Commands:
    - 'give {player} diamond 1'
    - 'tell {player} Congratulations!!!'
    - 'tell {player} You can add as many rewards as you want in the config.yml'